[build]
  builder = "nixpacks"
  buildCommand = "echo 'Building the application...'"

[deploy]
  healthcheckPath = "/test"
  healthcheckTimeout = 100
  restartPolicyType = "on_failure"

[env]
  PORT = "8000"
