[build]
  builder = "nixpacks"
  buildCommand = "pip install -r requirements.txt"

[deploy]
  buildCommand = "pip install -r requirements.txt"
  healthcheckPath = "/"
  healthcheckTimeout = 100
  restartPolicyType = "on_failure"
  # Eliminado startCommand para permitir configuración manual en Railway

[env]
  PORT = "8000"
