[build]
  builder = "nixpacks"
  buildCommand = "echo 'Building the application...'"

[deploy]
  startCommand = "uvicorn app_direct:app --host 0.0.0.0 --port 8000"
  healthcheckPath = "/test"
  healthcheckTimeout = 100
  restartPolicyType = "on_failure"

[env]
  PORT = "8000"
