[build]
  builder = "nixpacks"
  buildCommand = "echo 'Building the application...'"

[deploy]
  startCommand = "python start.py"
  healthcheckPath = "/"
  healthcheckTimeout = 100
  restartPolicyType = "on_failure"

[env]
  PORT = "8000"
