[build]
  builder = "nixpacks"
  buildCommand = "pip install -r requirements.txt"

[deploy]
  buildCommand = "pip install -r requirements.txt"
  healthcheckPath = "/test"
  healthcheckTimeout = 100
  restartPolicyType = "on_failure"
  startCommand = "bash start.sh"

[env]
  PORT = "8000"
