services:
  - type: web
    name: value-investing-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_direct:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 8000
      - key: ALPHAVANTAGE_API_KEY
        sync: false
      - key: CLAUDE_API_KEY
        sync: false
